/**:
  ros__parameters:
    data_root: "data/realflight_traj_new"
    timer_period: 0.01
    l: 1.0
    kq: 9.5
    kw: 3.4
    z_weight: 0.3
    thrust_bias: 0.0
    alpha_gain: 0.05
    initial_ready_delay: 5.0
    payload_is_enu: true
    log_path: ""
