/**:
  ros__parameters:
    data_root: "data/realflight_traj_new"
    timer_period: 0.01
    payload_odom_topic: "/payload_odom"
    payload_pose_topic: "/payload_odom"
    l: 1.0
    payload_mass: 0.220
    payload_radius: 0.125
    apply_payload_offset: false
    apply_init_pose_offset: false
    init_pose_topic: ""
    local_pos_offset: [0.0, 0.0, 0.0]
    acc_sp_timeout: 0.5
    kq: 9.5
    kw: 3.4
    z_weight: 0.0
    thrust_bias: 0.0
    thrust_to_weight_ratio: 7.90
    alpha_gain: 0.05
    initial_ready_delay: 5.0
    payload_is_enu: true
    log_path: "/home/carlson/ros2/realflight_ws/sitl_log"
    debug_log_path: "/home/carlson/ros2/realflight_ws/sitl_log"
    debug_log_period: 0.2
