/**:
  ros__parameters:
    mode: "sitl"
    payload_input: "odom"
    use_internal_state_machine: true
    use_payload_stamp_time: true
    command_all_drones: true
    lps_transient_local: true
    attitude_setpoint_topic: "in/vehicle_attitude_setpoint_v1"
    data_root: "data/realflight_traj_new_H (m2=0.1,rg=[0,0.028])"
    timer_period: 0.01
    payload_odom_topic: "/payload_odom"
    payload_pose_topic: "/payload_odom"
    l: 1.0
    payload_mass: 0.150
    payload_added_mass: 0.10
    payload_rp: [0.07, 0.0, 0.0]
    payload_radius: 0.125
    apply_payload_offset: false
    apply_init_pose_offset: false
    init_pose_topic: ""
    local_pos_offset: [0.0, 0.0, 0.0]
    acc_sp_timeout: 0.5
    kq: 9.5
    kw: 3.4
    z_weight: 0.30
    thrust_bias: 0.0
    thrust_to_weight_ratio: 7.90
    alpha_gain: 0.0
    initial_ready_delay: 5.0
    payload_is_enu: true
    enable_log: true
    enable_debug_log: true
    log_path: "/home/carlson/ros2/realflight_ws/sitl_log"
    debug_log_path: "/home/carlson/ros2/realflight_ws/sitl_log"
    debug_log_period: 0.2
